"""add_stocks_and_market_data_tables

Revision ID: b3253645e930
Revises: 300a3564cc60
Create Date: 2026-08-04 11:41:27.405501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3253645e930"
down_revision: str | Sequence[str] | None = "300a3564cc60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("exchange", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stocks")),
    )
    op.create_index(
        op.f("ix_stocks_deleted_at"), "stocks", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_stocks_symbol"), "stocks", ["symbol"], unique=True)
    op.create_table(
        "market_data",
        sa.Column("stock_id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "interval",
            sa.String(length=10),
            nullable=False,
            comment="Candle interval: 1m | 5m | 15m | 30m | 1h | 4h | 1d | 1wk",
        ),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=True,
            comment="Provider name: yahoo | upstox | zerodha | polygon",
        ),
        sa.Column(
            "provider_symbol",
            sa.String(length=100),
            nullable=True,
            comment=(
                "Symbol as used by the provider "
                "(may differ from the canonical application symbol)"
            ),
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
            name=op.f("fk_market_data_stock_id_stocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data")),
        sa.UniqueConstraint(
            "stock_id",
            "timestamp",
            "interval",
            name="uq_market_data_stock_timestamp_interval",
        ),
    )
    op.create_index(
        op.f("ix_market_data_deleted_at"), "market_data", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_data_stock_id"), "market_data", ["stock_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_data_timestamp"), "market_data", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_data_timestamp"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_stock_id"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_deleted_at"), table_name="market_data")
    op.drop_table("market_data")
    op.drop_index(op.f("ix_stocks_symbol"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_deleted_at"), table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
